"""add lead relationships to customers activities and followups

Revision ID: 04ca15ba59e0
Revises: f4cd6c0c5b90
Create Date: 2026-07-29 17:12:46.867272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ca15ba59e0'
down_revision: Union[str, Sequence[str], None] = 'f4cd6c0c5b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_activities', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.alter_column('customer_activities', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_customer_activities_lead_id'), 'customer_activities', ['lead_id'], unique=False)
    op.create_foreign_key(None, 'customer_activities', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.add_column('customers', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customers_lead_id'), 'customers', ['lead_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.add_column('followups', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.alter_column('followups', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_followups_lead_id'), 'followups', ['lead_id'], unique=False)
    op.create_foreign_key(None, 'followups', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followups', type_='foreignkey')
    op.drop_index(op.f('ix_followups_lead_id'), table_name='followups')
    op.alter_column('followups', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('followups', 'lead_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_lead_id'), table_name='customers')
    op.drop_column('customers', 'lead_id')
    op.drop_constraint(None, 'customer_activities', type_='foreignkey')
    op.drop_index(op.f('ix_customer_activities_lead_id'), table_name='customer_activities')
    op.alter_column('customer_activities', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('customer_activities', 'lead_id')
    # ### end Alembic commands ###
