"""add reminder sent at to followups

Revision ID: f4cd6c0c5b90
Revises: d3f6fa372870
Create Date: 2026-07-28 12:25:22.235330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4cd6c0c5b90'
down_revision: Union[str, Sequence[str], None] = 'd3f6fa372870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followups', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followups', 'reminder_sent_at')
    # ### end Alembic commands ###
